id = "amble"
name = "Amble"
version = "0.21.3"
schema_version = 1
authors = ["David Brown <djvbmd@protonmail.com>"]
description = "Extension to support the Amble game engine DSL."
repository = "https://github.com/pygmy-twylyte/zed-amble-ext.git"

[grammars.amble]
repository = "https://github.com/pygmy-twylyte/tree-sitter-amble.git"
rev = "b271f0c5af1c423c9225706c64fede5c7563ea27"

[language_servers.amble-lsp]
name = "Amble LSP"
language = "Amble"
